const plants = [

  {"englishName": "Hazel", "latinName": "Corylus avellana"},
  {"englishName": "Marjoram", "latinName": "Origanum majorana"},
  {"englishName": "Creeping thistle", "latinName": "Cirsium arvense"},
  {"englishName": "Foxglove (common)", "latinName": "Digitalis purpurea"},
  {"englishName": "Hawthorn or Whitethorn", "latinName": "Crataegus monogyna"},
  {"englishName": "Lemon Balm", "latinName": "Melissa officinalis"},
  {"englishName": "Bramble / Blackberry", "latinName": "Rubus fruticosus"},
  {"englishName": "Bluebell", "latinName": "Hyacinthoides non-scripta"},
  {"englishName": "Common Alder", "latinName": "Alnus glutinosa"},
  {"englishName": "Lovage", "latinName": "Levisticum officinale"},
  {"englishName": "Creeping buttercup", "latinName": "Ranunculus repens"},
  {"englishName": "Primrose (common)", "latinName": "Primula vulgaris"},
  {"englishName": "Italian Alder", "latinName": "Alnus cordata"},
  {"englishName": "Parsley", "latinName": "Petroselinum crispum"},
  {"englishName": "Rushes", "latinName": "Juncus spp."},
  {"englishName": "Herb Robert", "latinName": "Geranium robertianum"},
  {"englishName": "Ash", "latinName": "Fraxinus excelsior"},
  {"englishName": "Chives", "latinName": "Allium schoenoprasum"},
  {"englishName": "Field bindweed", "latinName": "Convolvulus arvensis"},
  {"englishName": "Montbretia", "latinName": "Crocosmia x crocosmiiflora"},
  {"englishName": "Silver Birch", "latinName": "Betula pendula"},
  {"englishName": "Bay", "latinName": "Laurus nobilis"},
  {"englishName": "Couch grass", "latinName": "Elymus repens"},
  {"englishName": "Spindle Tree", "latinName": "Euonymus europaeus"},
  {"englishName": "Mint", "latinName": "Mentha spp."},
  {"englishName": "Dock", "latinName": "Rumex spp."},
  {"englishName": "Meadowsweet", "latinName": "Filipendula ulmaria"},
  {"englishName": "Blackthorn", "latinName": "Prunus spinosa"},
  {"englishName": "Coriander", "latinName": "Coriandrum sativum"},
  {"englishName": "Dandelion", "latinName": "Taraxacum officinale"},
  {"englishName": "Sweetcorn", "latinName": "Zea mays"},
  {"englishName": "Sea-buckthorn", "latinName": "Hippophae rhamnoides"},
  {"englishName": "Fennel", "latinName": "Foeniculum vulgare"},
  {"englishName": "Stinging nettle", "latinName": "Urtica dioica"},
  {"englishName": "French Bean", "latinName": "Phaseolus vulgaris"},
  {"englishName": "Willow", "latinName": "Salix spp."},
  {"englishName": "Elder", "latinName": "Sambucus nigra"},
  {"englishName": "Thyme", "latinName": "Thymus vulgaris"},
  {"englishName": "Horsetail", "latinName": "Equisetum arvense"},
  {"englishName": "Runner Bean", "latinName": "Phaseolus coccineus"},
  {"englishName": "Dog Rose", "latinName": "Rosa canina"},
  {"englishName": "Comfrey", "latinName": "Symphytum officinale"},
  {"englishName": "Japanese knotweed", "latinName": "Fallopia japonica"},
  {"englishName": "Pea", "latinName": "Pisum sativum"},
  {"englishName": "Holly", "latinName": "Ilex aquifolium"},
  {"englishName": "Yarrow", "latinName": "Achillea millefolium"},
  {"englishName": "Ground Elder", "latinName": "Aegopodium podagraria"},
  {"englishName": "Cabbage", "latinName": "Brassica oleracea Capitata"},
  {"englishName": "Apple", "latinName": "Malus domestica"},
  {"englishName": "Borage", "latinName": "Borago officinalis"},
  {"englishName": "Smooth Sow thistle", "latinName": "Sonchus oleraceus"},
  {"englishName": "Brussel Sprout", "latinName": "Brassica oleracea Gemmifera"},
  {"englishName": "Plum", "latinName": "Prunus domestica"},
  {"englishName": "Lavendar (English)", "latinName": "Lavandula angustifolia"},
  {"englishName": "Scarlet Pimpernel", "latinName": "Anagallis arvensis"},
  {"englishName": "Broccoli", "latinName": "Brassica oleracea Italica"},
  {"englishName": "Pear", "latinName": "Pyrus communis"},
  {"englishName": "Rosemary", "latinName": "Rosmarinus officinalis"},
  {"englishName": "Charlock", "latinName": "Sinapis arvensis"},
  {"englishName": "Kale", "latinName": "Brassica oleracea Acephala"},
  {"englishName": "Walnut", "latinName": "Juglans regia"},
  {"englishName": "Sage", "latinName": "Salvia officinalis"},
  {"englishName": "Cleavers", "latinName": "Galium aparine"},
  {"englishName": "Kohl Rabi", "latinName": "Brassica oleracea Gongylodes"},
  {"englishName": "Sweet Chestnut", "latinName": "Castanea sativa"},
  {"englishName": "Tansy", "latinName": "Tanacetum vulgare"},
  {"englishName": "Speedwell", "latinName": "Veronica sp."},
  {"englishName": "Potato", "latinName": "Solanum tuberosum"},
  {"englishName": "Oak", "latinName": "Quercus spp."},
  {"englishName": "Basil", "latinName": "Ocimum basilicum"},
  {"englishName": "Hairy Bittercress", "latinName": "Cardamine hirsuta"},
  {"englishName": "Tomato", "latinName": "Solanum lycopersicum"},
  {"englishName": "Horse Chestnut", "latinName": "Aesculus hippocastanum"},
  {"englishName": "Chamomile", "latinName": "Matricaria recutita"},
  {"englishName": "Groundsel", "latinName": "Senecio vulgaris"},
  {"englishName": "Aubergine", "latinName": "Solanum melongena"},
  {"englishName": "Rowan", "latinName": "Sorbus aucuparia"},
  {"englishName": "Curry Plant", "latinName": "Helichrysum italicum"},
  {"englishName": "Red Dead Nettle", "latinName": "Lamium purpureum"},
  {"englishName": "Florence Fennel", "latinName": "Foeniculum vulgare"},
  {"englishName": "English Yew", "latinName": "Taxus baccata"},
  {"englishName": "Irish Yew", "latinName": "Taxus baccata ‘fastigata’"},
  {"englishName": "Dill", "latinName": "Anethum graveolens"},
  {"englishName": "Feverfew", "latinName": "Tanacetum parthenium"},
  {"englishName": "Fat Hen", "latinName": "Chenopodium album"},
  {"englishName": "Spring Onion", "latinName": "Allium cepa"},
  {"englishName": "Shallot", "latinName": "Allium cepa"},
  {"englishName": "Hornbeam", "latinName": "Carpinus betulus"},
  {"englishName": "Scots Pine", "latinName": "Pinus sylvestris"},
  {"englishName": "Salad Burnet", "latinName": "Sanguisorba minor"},
  {"englishName": "Red Shank", "latinName": "Persicaria maculosa Grey"},
  {"englishName": "Pumpkin", "latinName": "Cucurbita maxima"},
  {"englishName": "Cucumber", "latinName": "Cucumis sativus"},
  {"englishName": "Common Beech", "latinName": "Fagus sylvatica"},
  {"englishName": "Winter Savory", "latinName": "Satureja montana"},
  {"englishName": "Ramsoms", "latinName": "Allium ursinum"},
  {"englishName": "Red Campion", "latinName": "Silene dioica"},
  {"englishName": "Lettuce", "latinName": "Lactuca sativa"},
  {"englishName": "Courgette", "latinName": "Cucurbita pepo"}

  ];
  
  export default plants;

